enum Type{
    BinaryExpr,
    AssignExpr,
    FuncDecl,
    Program, 
    Literal,
    ForStmt,
    IfStmt,
    WhileStmt,
    VarDecl,
    ArrayExpr,
    PostUnaryExpr,
    PreUnaryExpr,
    BreakStmt,
    ReturnStmt,
    CondExpr,
    PropertyExpr,
    ArrayMemExpr,
    GroupingExpr,
    Identifier,
    InExpr,
    ForExpr,
    Enum,
    FuncParam,
    FuncExpr,
    SwitchStmt,
    SwitchCase,
    FallStmt,
    ObjectProperty,
    ClassDecl,
    MethodDecl,
    ArrowFuncDecl
}

export = Type